# Used when running locally.
# Use kubectl to port forward.
apiVersion: v1
kind: Service
metadata:
  name: local-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: websocket-server
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
