
apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-server-deployment # Must be unique within a namespace.
spec:
  selector:
    matchLabels:
      app: websocket-server
  replicas: 3
  template:
    metadata:
      labels:
        app: websocket-server # Need a label so all the logs can be obtained.
    spec:
      containers:
      - name: websocket-server
        image: websocket-server:latest
        imagePullPolicy: Never # This is needed when running locally: https://kind.sigs.k8s.io/docs/user/quick-start/#loading-an-image-into-your-cluster
        ports:
        - containerPort: 8080
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
